llm:
  model_provider: qwen #qwen #openai
  model: qwen1.5-110b-chat
  url: "https://open.bigmodel.cn/api/paas/v4/"

# qwen1.5-72b-chat   qwen1.5-110b-chat
# qwen-turbo  qwen-plus   qwen-max   qwen-long
# https://dashscope.aliyun.com/

# glm-4
# https://open.bigmodel.cn


server_port: 8087
